In [17]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

import argparse
from os import path
import easydict

In [19]:
train_data = pd.read_csv('./data/u1.base', sep='\t', header=None)
train_data.rename(columns={0:'user_id', 1:'item_id', 2:'rating', 3:'time_stamp'}, inplace=True)
train_data.head()

user_id  item_id  rating  time_stamp
0        1        1       5   874965758
1        1        2       3   876893171
2        1        3       4   878542960
3        1        4       3   876893119
4        1        5       3   889751712

In [20]:
train_data.drop('time_stamp', axis=1, inplace=True)
train_data.head()

user_id  item_id  rating
0        1        1       5
1        1        2       3
2        1        3       4
3        1        4       3
4        1        5       3

In [22]:
R = train_data.pivot_table('rating', index='user_id', columns='item_id').fillna(0)
print(R.shape)
R.head()

(943, 1650)


item_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                              ...   
1         5.0   3.0   4.0   3.0   3.0   0.0   4.0   1.0   5.0   0.0  ...   
2         4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

item_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                              
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 1650 columns]

In [43]:
print(R.values.shape)
a = np.array(R.values)
print(a)

(943, 1650)
[[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]]


In [44]:
test_data = pd.read_csv('./data/u1.test', sep='\t', header=None)
test_data.rename(columns={0:'user_id', 1:'item_id', 2:'rating', 3:'time_stamp'}, inplace=True)
test_data.drop('time_stamp', axis=1, inplace=True)
test_data.head()

user_id  item_id  rating
0        1        6       5
1        1       10       3
2        1       12       5
3        1       14       5
4        1       17       3

In [46]:
T = test_data.values
print(T)

[[  1   6   5]
 [  1  10   3]
 [  1  12   5]
 ...
 [459 934   3]
 [460  10   3]
 [462 682   5]]


In [50]:
a=T[:,0]
b=T[:,:-1]
print(b)

[[  1   6]
 [  1  10]
 [  1  12]
 ...
 [459 934]
 [460  10]
 [462 682]]
